name: Release project - dry run
on:
  push:
    branches:
      - "v2"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Release
        uses: huggingface/semver-release-action@latest
        with:
          dryRun: true